# GitHubì˜ ì•¡ì…˜ íƒ­ì—ì„œ í‘œì‹œë˜ëŠ” ì›Œí¬í”Œë¡œìš°ì˜ ì´ë¦„
name: Build and Test

on:
  # develop ë¸Œëœì¹˜ì— push ë‚˜ pull request ì´ë²¤íŠ¸ê°€ ì¼ì–´ë‚¬ì„ë•Œ í•´ë‹¹ workflowë¥¼ íŠ¸ë¦¬ê±°
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# workflowì˜ ì‹¤í–‰ì€ í•˜ë‚˜ ì´ìƒì˜ jobìœ¼ë¡œ êµ¬ì„± ë¨. ì—¬ê¸°ì„œëŠ” "build" ë¼ëŠ” single job ìœ¼ë¡œ êµ¬ì„±

jobs:
  build:
    runs-on: macos-latest     # jobì´ ì‹¤í–‰ë  í™˜ê²½ - ìµœì‹  mac os

    # Stepì€ jobì˜ ì¼ë¶€ë¡œ ì‹¤í–‰ë  ì¼ë ¨ì˜ taskë“¤ì„ ë‚˜íƒ€ëƒ„
    steps:
    # uses í‚¤ì›Œë“œë¥¼ í†µí•´ Github Actionsì—ì„œ ê¸°ë³¸ìœ¼ë¡œ ì œê³µí•˜ëŠ” ì•¡ì…˜ì„ ì‚¬ìš© ê°€ëŠ¥. ì•„ë˜ ì•¡ì…˜ì€ repository ì— ì²´í¬ì•„ì›ƒí•˜ëŠ” ê²ƒ
    - uses: actions/checkout@v2
    # shell ì´ìš©í•´ì„œ í•˜ë‚˜ì˜ command ìˆ˜í–‰
    - name: Build the project ğŸ› 
      run: |
        xcodebuild clean build -project DearMe/DearMe.xcodeproj -scheme DearMe -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.0'
    
    - name: Run tests ğŸ§ª
      run: |
        xcodebuild test -project Popcorn-iOS/Popcorn-iOS.xcodeproj -scheme DearMe -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.0'
